#!/bin/bash
# Usage: agent_ask <agent_name> <prompt...>
AGENT="${1:?Usage: agent_ask <agent_name> <prompt...>}"
shift
docker exec \
  -e TERM="${TERM:-xterm-256color}" \
  -e COLORTERM="${COLORTERM:-truecolor}" \
  -e TMUX="${TMUX:-}" \
  -e STY="${STY:-}" \
  "$AGENT" term-llm ask "@$AGENT" --yolo "$@"
