package contain

import (
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/samsaffron/term-llm/internal/config"
)

//go:embed images/**
var embeddedImages embed.FS

const managedImageMarker = "# Generated by term-llm contain."

const managedImageHeader = managedImageMarker + `
# Image asset: agent
# Managed: true

`

var builtinImageNames = []string{"agent"}

type ImageSyncResult struct {
	Name    string
	Dir     string
	Files   []string
	Updated bool
}

// ImagesRoot returns the directory containing managed contain image assets.
func ImagesRoot() (string, error) {
	configDir, err := config.GetConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(configDir, "images"), nil
}

// ImageDir returns the managed directory for an image asset.
func ImageDir(name string) (string, error) {
	root, err := ImagesRoot()
	if err != nil {
		return "", err
	}
	return filepath.Join(root, name), nil
}

// AgentImageDockerfilePath returns the stable managed legacy Arch Dockerfile
// path for the built-in agent runtime image.
func AgentImageDockerfilePath() (string, error) {
	dir, err := ImageDir("agent")
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "Dockerfile"), nil
}

// AgentImageHash returns a deterministic short hex fingerprint of the embedded
// agent image build context. The hash changes whenever any embedded file under
// images/agent is added, removed, renamed, or modified. It is suffixed onto
// the agent image tag so changes to embedded content force a fresh image
// instead of silently reusing a cached tag.
func AgentImageHash() (string, error) {
	base := filepath.ToSlash(filepath.Join("images", "agent"))
	type entry struct {
		path string
		data []byte
	}
	var entries []entry
	err := fs.WalkDir(embeddedImages, base, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(base, path)
		if err != nil {
			return err
		}
		data, err := embeddedImages.ReadFile(path)
		if err != nil {
			return err
		}
		entries = append(entries, entry{path: filepath.ToSlash(rel), data: data})
		return nil
	})
	if err != nil {
		return "", fmt.Errorf("walk embedded agent image: %w", err)
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].path < entries[j].path })

	h := sha256.New()
	for _, e := range entries {
		fmt.Fprintf(h, "%s\x00%d\x00", e.path, len(e.data))
		h.Write(e.data)
		h.Write([]byte{0})
	}
	return hex.EncodeToString(h.Sum(nil))[:12], nil
}

// BuiltinImageNames returns supported managed image asset names.
func BuiltinImageNames() []string {
	names := append([]string(nil), builtinImageNames...)
	sort.Strings(names)
	return names
}

// AgentImageBootstrapSkillNames returns the term-llm skill names bundled into
// the managed agent image bootstrap. These are copied into
// ~/.config/term-llm/skills/ on first boot of an agent contain workspace.
func AgentImageBootstrapSkillNames() ([]string, error) {
	base := filepath.ToSlash(filepath.Join("images", "agent", "bootstrap", "skills"))
	entries, err := embeddedImages.ReadDir(base)
	if err != nil {
		return nil, fmt.Errorf("read embedded agent bootstrap skills: %w", err)
	}
	var names []string
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		if _, err := embeddedImages.ReadFile(filepath.ToSlash(filepath.Join(base, entry.Name(), "SKILL.md"))); err != nil {
			if errors.Is(err, fs.ErrNotExist) {
				continue
			}
			return nil, err
		}
		names = append(names, entry.Name())
	}
	sort.Strings(names)
	return names, nil
}

// SyncImage writes a managed embedded image asset into the user's config dir.
// Existing managed files are updated. Non-managed existing files are not
// overwritten unless force is true.
func SyncImage(name string, force bool) (ImageSyncResult, error) {
	if name == "" {
		name = "agent"
	}
	if name != "agent" {
		return ImageSyncResult{}, fmt.Errorf("unknown contain image %q: supported images: %s", name, strings.Join(BuiltinImageNames(), ", "))
	}
	dir, err := ImageDir(name)
	if err != nil {
		return ImageSyncResult{}, err
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return ImageSyncResult{}, err
	}

	result := ImageSyncResult{Name: name, Dir: dir}
	// The managed marker intentionally lives only in Dockerfiles so it cannot
	// leak into bootstrap prompts. Any managed Dockerfile marks the whole image
	// directory as safe for updating marker-free companion assets.
	managedDir := false
	if matches, err := filepath.Glob(filepath.Join(dir, "Dockerfile*")); err == nil {
		for _, path := range matches {
			if existing, err := os.ReadFile(path); err == nil && isManagedImageFile(existing) {
				managedDir = true
				break
			} else if err != nil && !os.IsNotExist(err) {
				return ImageSyncResult{}, err
			}
		}
	} else {
		return ImageSyncResult{}, err
	}
	base := filepath.ToSlash(filepath.Join("images", name))
	err = fs.WalkDir(embeddedImages, base, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(base, path)
		if err != nil {
			return err
		}
		rel, err = safeTemplateTargetPath(filepath.ToSlash(rel))
		if err != nil {
			return err
		}
		data, err := embeddedImages.ReadFile(path)
		if err != nil {
			return err
		}
		data = addManagedImageHeader(rel, data)
		target := filepath.Join(dir, rel)
		if err := writeManagedImageFile(target, data, force, managedDir, isImageDockerfile(rel)); err != nil {
			return err
		}
		result.Files = append(result.Files, target)
		result.Updated = true
		return nil
	})
	if err != nil {
		return ImageSyncResult{}, err
	}
	sort.Strings(result.Files)
	return result, nil
}

func writeManagedImageFile(path string, data []byte, force, managedDir, dockerfile bool) error {
	if existing, err := os.ReadFile(path); err == nil {
		if !force {
			if dockerfile {
				if !isManagedImageFile(existing) {
					return fmt.Errorf("refusing to overwrite non-managed image file %s; copy/fork it or rerun with --force", path)
				}
			} else if !managedDir && !isManagedImageFile(existing) {
				return fmt.Errorf("refusing to overwrite non-managed image file %s; copy/fork it or rerun with --force", path)
			}
		}
	} else if !os.IsNotExist(err) {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}

func addManagedImageHeader(rel string, data []byte) []byte {
	if !isImageDockerfile(rel) || isManagedImageFile(data) {
		return data
	}
	text := string(data)
	if strings.HasPrefix(text, "# syntax=") {
		if idx := strings.IndexByte(text, '\n'); idx >= 0 {
			return []byte(text[:idx+1] + managedImageHeader + text[idx+1:])
		}
		return []byte(text + "\n" + managedImageHeader)
	}
	return []byte(managedImageHeader + text)
}

func isImageDockerfile(rel string) bool {
	base := filepath.Base(filepath.ToSlash(rel))
	return base == "Dockerfile" || strings.HasPrefix(base, "Dockerfile.")
}

func isManagedImageFile(data []byte) bool {
	return strings.Contains(string(data), managedImageMarker)
}
